// Generated by React Router

import "react-router"

declare module "react-router" {
  interface Register {
    pages: Pages
    routeFiles: RouteFiles
    routeModules: RouteModules
  }
}

type Pages = {
  "/": {
    params: {};
  };
  "/recommendations": {
    params: {};
  };
  "/api/recommendations": {
    params: {};
  };
  "/thespot": {
    params: {};
  };
  "/map": {
    params: {};
  };
  "/account": {
    params: {};
  };
  "/account/edit": {
    params: {};
  };
  "/create-profile": {
    params: {};
  };
  "/login": {
    params: {};
  };
  "/otherbar": {
    params: {};
  };
  "/beerloading": {
    params: {};
  };
  "/storytelling": {
    params: {};
  };
  "/loadingrecommendation": {
    params: {};
  };
};

type RouteFiles = {
  "root.tsx": {
    id: "root";
    page: "/" | "/recommendations" | "/api/recommendations" | "/thespot" | "/map" | "/account" | "/account/edit" | "/create-profile" | "/login" | "/otherbar" | "/beerloading" | "/storytelling" | "/loadingrecommendation";
  };
  "./routes/home.jsx": {
    id: "routes/home";
    page: "/";
  };
  "./routes/recommendations.jsx": {
    id: "routes/recommendations";
    page: "/recommendations";
  };
  "./routes/api.recommendations.ts": {
    id: "routes/api.recommendations";
    page: "/api/recommendations";
  };
  "./routes/thespot.jsx": {
    id: "routes/thespot";
    page: "/thespot";
  };
  "./routes/map.jsx": {
    id: "routes/map";
    page: "/map";
  };
  "./routes/account.jsx": {
    id: "routes/account";
    page: "/account";
  };
  "./routes/editaccount.jsx": {
    id: "routes/editaccount";
    page: "/account/edit";
  };
  "./routes/createprofile.jsx": {
    id: "routes/createprofile";
    page: "/create-profile";
  };
  "./routes/login.jsx": {
    id: "routes/login";
    page: "/login";
  };
  "./routes/otherbar.jsx": {
    id: "routes/otherbar";
    page: "/otherbar";
  };
  "./routes/beerloading.jsx": {
    id: "routes/beerloading";
    page: "/beerloading";
  };
  "./routes/storytelling.jsx": {
    id: "routes/storytelling";
    page: "/storytelling";
  };
  "./routes/loadingrecommendation.jsx": {
    id: "routes/loadingrecommendation";
    page: "/loadingrecommendation";
  };
};

type RouteModules = {
  "root": typeof import("./app/root.tsx");
  "routes/home": typeof import("./app/./routes/home.jsx");
  "routes/recommendations": typeof import("./app/./routes/recommendations.jsx");
  "routes/api.recommendations": typeof import("./app/./routes/api.recommendations.ts");
  "routes/thespot": typeof import("./app/./routes/thespot.jsx");
  "routes/map": typeof import("./app/./routes/map.jsx");
  "routes/account": typeof import("./app/./routes/account.jsx");
  "routes/editaccount": typeof import("./app/./routes/editaccount.jsx");
  "routes/createprofile": typeof import("./app/./routes/createprofile.jsx");
  "routes/login": typeof import("./app/./routes/login.jsx");
  "routes/otherbar": typeof import("./app/./routes/otherbar.jsx");
  "routes/beerloading": typeof import("./app/./routes/beerloading.jsx");
  "routes/storytelling": typeof import("./app/./routes/storytelling.jsx");
  "routes/loadingrecommendation": typeof import("./app/./routes/loadingrecommendation.jsx");
};