// Generated by React Router

import "react-router"

declare module "react-router" {
  interface Register {
    pages: Pages
    routeFiles: RouteFiles
    routeModules: RouteModules
  }
}

type Pages = {
  "/": {
    params: {};
  };
  "/loadingrecommendation": {
    params: {};
  };
  "/api/recommendations": {
    params: {};
  };
  "/recommendations": {
    params: {};
  };
  "/create-profile": {
    params: {};
  };
  "/account/edit": {
    params: {};
  };
  "/storytelling": {
    params: {};
  };
  "/beerloading": {
    params: {};
  };
  "/otherbar": {
    params: {};
  };
  "/account": {
    params: {};
  };
  "/thespot": {
    params: {};
  };
  "/login": {
    params: {};
  };
  "/map": {
    params: {};
  };
};

type RouteFiles = {
  "root.tsx": {
    id: "root";
    page: "/" | "/loadingrecommendation" | "/api/recommendations" | "/recommendations" | "/create-profile" | "/account/edit" | "/storytelling" | "/beerloading" | "/otherbar" | "/account" | "/thespot" | "/login" | "/map";
  };
  "routes/loadingrecommendation.jsx": {
    id: "routes/loadingrecommendation";
    page: "/loadingrecommendation";
  };
  "routes/api.recommendations.ts": {
    id: "routes/api.recommendations";
    page: "/api/recommendations";
  };
  "routes/recommendations.jsx": {
    id: "routes/recommendations";
    page: "/recommendations";
  };
  "routes/create-profile.jsx": {
    id: "routes/create-profile";
    page: "/create-profile";
  };
  "routes/account_.edit.jsx": {
    id: "routes/account_.edit";
    page: "/account/edit";
  };
  "routes/storytelling.jsx": {
    id: "routes/storytelling";
    page: "/storytelling";
  };
  "routes/beerloading.jsx": {
    id: "routes/beerloading";
    page: "/beerloading";
  };
  "routes/otherbar.jsx": {
    id: "routes/otherbar";
    page: "/otherbar";
  };
  "routes/account.jsx": {
    id: "routes/account";
    page: "/account";
  };
  "routes/thespot.jsx": {
    id: "routes/thespot";
    page: "/thespot";
  };
  "routes/_index.jsx": {
    id: "routes/_index";
    page: "/";
  };
  "routes/login.jsx": {
    id: "routes/login";
    page: "/login";
  };
  "routes/map.jsx": {
    id: "routes/map";
    page: "/map";
  };
};

type RouteModules = {
  "root": typeof import("./app/root.tsx");
  "routes/loadingrecommendation": typeof import("./app/routes/loadingrecommendation.jsx");
  "routes/api.recommendations": typeof import("./app/routes/api.recommendations.ts");
  "routes/recommendations": typeof import("./app/routes/recommendations.jsx");
  "routes/create-profile": typeof import("./app/routes/create-profile.jsx");
  "routes/account_.edit": typeof import("./app/routes/account_.edit.jsx");
  "routes/storytelling": typeof import("./app/routes/storytelling.jsx");
  "routes/beerloading": typeof import("./app/routes/beerloading.jsx");
  "routes/otherbar": typeof import("./app/routes/otherbar.jsx");
  "routes/account": typeof import("./app/routes/account.jsx");
  "routes/thespot": typeof import("./app/routes/thespot.jsx");
  "routes/_index": typeof import("./app/routes/_index.jsx");
  "routes/login": typeof import("./app/routes/login.jsx");
  "routes/map": typeof import("./app/routes/map.jsx");
};